version: "3.9"
services:
  webapp:
    depends_on:
      - mongodb
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 8080:8080

  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=grades
      - PUID=1000
      - PGID=1000
    volumes:
      - ./server/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
